import PySimpleGUI as sg
import openpyxl as px
import warnings
import pyperclip

path = r".xlsx"
sht = "INDEX"
num = 0

ico = "AAABAAIAEBAAAAEAIABoBAAAJgAAACAgAAABACAAKBEAAI4EAAAoAAAAEAAAACAAAAABACAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmeAAAJqcAAAAAAAAAAAAAJngAACdOAAAAAAAAJy4AACagAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKFhz0ANhZf8Hb27/C0Fc8r3q/XgMVGL/AlNZ/26Jp6IDYmX/BcCg/wAAJxoAAAAAAAAAAAAAAAAAAAAAAAAiDzPAsv8Fspn/A5Z/xwbLqf8FvZz/Bs6rywNnaMEemIn/AAAmmwAAAAACUFtwAAAAAAAAJl8NANcTAAAAAAAAIR8Eg3r/AmRk/gAAAAAAACMWAAAm5wAAIAgAAAAAAAAAAAAAAAAAAAAAAAAmtf///14AAAACAQA1+gAHKucGzarnBcOj/wNsa/sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiJSlKb/8GyKf/L6Wr/xfGsf8Fp5KmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIs6a4Bs2q/wbNqv9d3sj/KMevQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4RO5QAACanAAAoOgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAIAAAAEAAAAABACAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmLx8mSYVQY4H/Ii5W/1Jlg/oCBy1sAAAAAAAAAAAAAAAAAAAlYT1MbP9QYoD9AAAjFgAAAAAAAAAAAAAnaU5ffvMcJUv/AAAlNwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJYhWaoj/CDFL/wIqQv8BKkH/QHuO/3KNqP8lLlHpAAAqBgABJ7Jaboz/BzJO/zduiP8fJkn/AAAnNAwQN30uRWv/BTRO/wS4l/8BFTT/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeJWv/gRXX/8Gzar/Bs2q/wKbf/8Gzar/BZWJ/77q/v88Sm77u+b7/wRdY/8Evp3/AZV6/wRTXv9+nrz/gKG//wbJqP8BHkD/AAIn/wbLqf8AACW4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJrNKXoD/Bs2q/wbNqv8Gzar/AZN4/wSzlP8Gzar/Bsam/xWynv8Fno3/Bs2q/wF+bv8AJTv/Bsyp/wSljP8DmIL/BrSa/wAKKzUAACQHA2Zo/wN7dugAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAm2zO8s/8Gzar/Bs2q/wNiaP8AACV0AzRKvgSCef8Gyqf/AZZ6/wS6mv8Fmon/AAAmWAAAAAIFPVDfSJuV/yF0ef8AACVuAAAAAAAAAAAAACRUA2Jm/wAAJoUAAAAAAAAAAAAAAAAAACdPAAAAAwAAAAAAAAAAAAAAAAAAAAAAACbbCYyH/wXGpP8Fyqf/AAMo/wAAAAAAAAAAAAAkVA+Hff9LrZ3/A351/wAAJW4AAAAAAAAAAAAAAAAAAAADAAAAAwAAAAAAAAAAAAAAAAAAAAACAyqeBIR8/ywyUuQAACchAAAmFAMASugCAD/rAAAkBwAAAAAAAAAAAAAAAAAAJtsHiH//AZN4/wGTeP8AAif/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZQAAAAMAAAAAAAAzBRIAthwBADjrAAAm4wETOeMAACbjAAAm+wySjv8Evp3/AZN4/wACJ/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACMddVeo+wWbiv8Hf4X/Brad/w/Jrv97ndj/MLy6/wbNqv8Gzar/AAMo/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKSynieH/Bs2q/wbNqv8Gyaj/FMev/7SG7v8ov7f/Bs2q/wbNqv8AAyj2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApLAbDpP8Fmor/Bs2q/wSciv8BFTT/Bs2q/wbNqv8Gzar/Bbid/wBmZgUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAm8wfNqv8Gzar/Bs2q/wbNqv8Gzar/Bs2q/wbNqv8Ko5D+AABABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQxbpCf/0DYvf8Gzar/Bs2q/wbNqv8Gzar/eqCm/wAAJSkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRNVFZxg1loe/4LWGD/K15r/0JCXZcAACY9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

#-------------------------------------------------------------------------
def excel(n):

    
            # エクセルファイルの取り込み
        wb = px.load_workbook(path)
        ws = wb[sht]

            # １行目（列名のセル）
        header_cells = ws[1]

            # ２行目以降（データ）
        student_list = []
        for row in ws.iter_rows(min_row=2):
            row_dic = {}
                # セルの値を「key-value」で登録
            for k, v in zip(header_cells, row):
                row_dic[k.value] = v.value
            student_list.append(row_dic)

        nv = [s["申請番号"] for s in student_list]
        return ws,nv

#-------------------------------------------------------------------------
warnings.simplefilter('ignore')
sg.theme('Purple')   # デザインテーマの設定

    # ウィンドウに配置するコンポーネント


menu_def = [['ファイル',['Open','Save']],
            ['設定',['Theme設定']],
            ]

comb = []

layout = [
            #[sg.Menu(menu_def)],
            [sg.Combo(comb, default_value="申請番号",key="ad", size=(23,1)),(sg.Button("CP",key="copy",size=(2,1)))],
	    [sg.InputText(key="input",size=(24,2)),sg.Button('OK',key="ok")],#,sg.Checkbox("最前列",default=True)
        
            [sg.Output(key="output",size=(26,5))]
            
        ]
#subwindow



    # ウィンドウの生成----------------------------------------------------
window = sg.Window('事業者検索',
                    layout,location=(1675,850),
                    keep_on_top=True,resizable=True,
                    alpha_channel=0.9, return_keyboard_events=True)

  # イベントループ
while True:
    event, values = window.read()
    if event == sg.WIN_CLOSED or event == '終了':
        print("終了")
        break
    elif event == 'ok' or event == '\r':#--------------------------------------------------
        n = int(values["input"])
        ws,nv = excel(n)
        try:     
            index = nv.index(n) + 2
            print("--"*20)
            for i in range(1,6):
                t = ws.cell(column=i, row=1).value
                p = ws.cell(column=i, row=index).value
                i += 1
                print(t,p)
                
        except ValueError as e:
            print("--"*21)
            print("その申請番号はありません!\n")
            print("--"*21)
        finally:    
            window['input']. Update('')

            com = ws.cell(column=2, row=index).value
            name = ws.cell(column=3, row=index).value
            tel = ws.cell(column=5, row=index).value
            tanto = ws.cell(column=4, row=index).value
            mail1 = ws.cell(column=7, row=index).value
            mail2 = ws.cell(column=8, row=index).value
            com = com.replace("（株）","株式会社")
            comb.clear()
            one = mail1
            two = "No.D_{0}_書類の修正について".format(n)
            three = "{0}\n{1}様\n\nいつも大変お世話になっております。\n {2}でございます。".format(com,name,tanto)
            fore = "{0} {1} メールのご確認・送信お願い致します。 ".format(n,com)
            five = tanto
            comb.append(str(n))
            comb.append(mail1)
            comb.append(mail2)
            comb.append(two)
            comb.append(three)
            comb.append(fore)
            window['ad']. Update(comb,comb)
    elif event == "copy":#-------------------------------------------------------
        
           al = values['ad']
           name = window["ad"].get()
           pyperclip.copy(name)
           sg.popup_quick(name,title="Copyed!!",icon=ico)
        
            #window["IT"]. Update("")
window.close()

